services:
  postgres:
    image: postgres:15.1
    command: ["-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vetka
    ports:
      - "5432:5432"
    networks:
      - vetka

  redis:
    image: redis:7.0
    command: ["redis-server", "--requirepass", "redis", "--loglevel", "verbose"]
    ports:
      - "6379:6379"
    networks:
      - vetka

networks:
  vetka:
    driver: bridge
